// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_tw16ETWFxDt6_xf9NDnhb5AgugkEZuE',
    appId: '1:362798120813:web:7fc2555faea8debfab6464',
    messagingSenderId: '362798120813',
    projectId: 'salim-cbt',
    authDomain: 'salim-cbt.firebaseapp.com',
    storageBucket: 'salim-cbt.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx9dXJuwC010SZ3OVnEZh2ZFDXGysS6os',
    appId: '1:362798120813:android:f9bc18a633b41e11ab6464',
    messagingSenderId: '362798120813',
    projectId: 'salim-cbt',
    storageBucket: 'salim-cbt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTuRGrNSX_bfOljEc0HkYbPuv31kQcBxA',
    appId: '1:362798120813:ios:c5fbc1e0dfaa878eab6464',
    messagingSenderId: '362798120813',
    projectId: 'salim-cbt',
    storageBucket: 'salim-cbt.appspot.com',
    iosBundleId: 'com.example.salimCbt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTuRGrNSX_bfOljEc0HkYbPuv31kQcBxA',
    appId: '1:362798120813:ios:a61eb6f114b6f098ab6464',
    messagingSenderId: '362798120813',
    projectId: 'salim-cbt',
    storageBucket: 'salim-cbt.appspot.com',
    iosBundleId: 'com.example.salimCbt.RunnerTests',
  );
}
